  
name: ive_flutter_core
description: Core assets for InnoVet Europe Flutter projects
version: 1.2.2
homepage: https://www.harriercentral.com/
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ^3.13.9

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: 5.2.0 
  freezed_annotation: 2.4.1
  intl: 0.18.1
  json_annotation: 4.8.1
  photo_view: 0.14.0 
  qr_flutter: 4.1.0 
  
dev_dependencies:
  build_runner: 2.4.6
  freezed: 2.4.5
  json_serializable: 6.7.1

