  
name: ive_flutter_core
description: Core assets for InnoVet Europe Flutter projects
version: 1.1.1
homepage: https://www.harriercentral.com/
publish_to: none

environment:
  sdk: ">=2.14.3 <3.0.0"
  flutter: ^2.5.2

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.0.0 # updated on Mar 25, 21 from 4.1.2+1 #updated on May 7 from 3.1.0 
  freezed_annotation: ^0.15.0
  intl: ^0.17.0 # updated on Mar 25, 21 from 0.17.0-nullsafety.2
  json_annotation: ^4.3.0
  photo_view: ^0.13.0 # updated on Mar 25, 21 from 0.10.2 # updated 23 Aug 2020 from 0.10.0 # updated 17 Aug 2020 from 0.9.2 #updated on May 7 from 0.4.2
  qr_flutter: ^4.0.0 # updated on Mar 25, 21 from 3.2.0  #updated on May 7 from 2.1.0+55
  
dev_dependencies:
  build_runner: ^2.1.4 # updated on Mar 25, 21 from 1.10.3  # updated on 22 Oct 2020 from 1.10.1 # updated 05 Aug 2020 from 1.10.0 # updated on 21 Jun 2020 from 1.8.1
  json_serializable: ^6.0.1 # updated on 25 Mar 2021 from 3.5.0  # updated on 22 Oct 2020 from 3.4.0 # updated 17 Aug 2020 from 3.3.0
  freezed: ^0.15.0+1

