  
name: ive_flutter_core
description: Core assets for InnoVet Europe Flutter projects
version: 1.2.0
homepage: https://www.harriercentral.com/
publish_to: none

environment:
  sdk: ">=2.14.3 <3.0.0"
  flutter: ^3.7.7

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.1.0 
  freezed_annotation: ^2.2.0
  intl: ^0.18.0 
  json_annotation: ^4.8.0
  photo_view: ^0.14.0 
  qr_flutter: ^4.0.0 
  
dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2

