  
name: ive_flutter_core
description: Core assets for InnoVet Europe Flutter projects
version: 1.1.2
homepage: https://www.harriercentral.com/
publish_to: none

environment:
  sdk: ">=2.14.3 <3.0.0"
  flutter: ^2.10.1

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.0.0 
  freezed_annotation: ^1.1.0
  intl: ^0.17.0 
  json_annotation: ^4.3.0
  photo_view: ^0.13.0 
  qr_flutter: ^4.0.0 
  
dev_dependencies:
  build_runner: ^2.1.4 
  json_serializable: ^6.0.1 
  freezed: ^1.1.1

