  
name: ive_flutter_core
description: Core assets for InnoVet Europe Flutter projects
version: 1.2.4
homepage: https://www.harriercentral.com/
publish_to: none

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: 3.22.2

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.2.1 
  freezed_annotation: 2.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  photo_view: ^0.15.0 
  qr_flutter: 4.1.0 
  
dependency_overrides:
  meta: 1.8.0
  
dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

