  
name: ive_flutter_core
description: Core assets for InnoVet Europe Flutter projects
version: 1.0.32
author: InnoVet Europe
homepage: https://www.innovetusa.com/

environment:
  sdk: ">=2.7.0-0.0 <3.0.0"
  flutter: ^1.22.2

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^4.1.2+1 #updated on May 7 from 3.1.0 
  intl: ^0.16.1
  photo_view: ^0.10.2 # updated 23 Aug 2020 from 0.10.0 # updated 17 Aug 2020 from 0.9.2 #updated on May 7 from 0.4.2
  qr_flutter: ^3.2.0  #updated on May 7 from 2.1.0+55
  
dev_dependencies:
  build_runner: ^1.10.3  # updated on 22 Oct 2020 from 1.10.1 # updated 05 Aug 2020 from 1.10.0 # updated on 21 Jun 2020 from 1.8.1
  json_serializable: ^3.5.0  # updated on 22 Oct 2020 from 3.4.0 # updated 17 Aug 2020 from 3.3.0
